a=User.new(
  verify:		'hr',
  bank_id:		10000,
  title:		'人事经理',
  city:			'上海',
  id:			'30001',
  mobile:		'13916330001',
  user_name:		'潘其多',
  true_name:		'潘其多',
  :avatar => File.open(File.join(Rails.root, 'app', 'assets','images','潘其多.png')),
  email:		'pqd@test.com',
  password:		'11111111',
  password_confirmation:'11111111',
  user_type:		'人事',
  base_salary:		'10000',
  month_num:		'13',
  bonus:		'50000',
  housing:		'10200',
  transport:		'56000',
  birthday:		'1982-9-11',
  stock:		'',
  stock_num:		'',
  industry:		'快消',
  summaries_attributes:	{first:{content:'负责公司的招聘，培训，薪资福利和绩效考核'},
	  		second:{content:'制定公司的工资福利架构'},
			third: {content:'与CEO一起完成年度的招聘计划'}},
  works_attributes:	
  			{first: {title:  'HR Manager',
	  			employer:'某公司',
				industry:'信息技术和人力资源',
				join_date:'2012-09-3',
				leave_date:'2014-10-31',
				job_scope:'领导20个人的人力资源部门',
				}},
  educations_attributes:{first: {enter_school:'1999-9-1',
	  			leave_school:'2003-9-1',
				major:'计算机',
				degree:'本科',
				school:'复旦大学'}}
  			)
a.skip_confirmation!
a.save!
