a=User.new(
  title:		'高级猎头顾问',
  city:			'上海',
  id:			'20001',
  mobile:		'13916320001',
  user_name:		'Sophy Song',
  true_name:		'宋优优',
  :avatar => File.open(File.join(Rails.root, 'app', 'assets','images','宋优优.png')),
  email:		'syy@test.com',
  password:		'11111111',
  password_confirmation:'11111111',
  user_type:		'猎头',
  base_salary:		'10000',
  month_num:		'13',
  bonus:		'50000',
  housing:	'10200',
  transport:'56000',
  birthday:	'1982-9-11',
  stock:		'',
  stock_num:	'',
  industry:		'快消',
  focus_job1:		'采购经理',
  summaries_attributes:	{first:{content:'主要负责store & retail的招聘,维护和发展客户关系'},
	  		second:{content:'选择和推荐合适的候选人并进行面试'},
			third: {content:'流程管理,工资商议以及候选人的follow-up'}},
  works_attributes:	
  			{first: {title:  '高级猎头顾问',
	  			employer:'华德士',
				industry:'猎头',
				join_date:'2001-09-3',
				leave_date:'2014-10-31',
				job_scope:'开发猎头业务,带领猎头团队进行人才搜寻'
				}},
  educations_attributes:{first: {enter_school:'1997-9-1',
	  			leave_school:'2001-9-1',
				major:'人力资源管理',
				degree:'本科',
				school:'复旦大学大学'}}
  			)
b=User.new(
  title:		'猎头顾问',
  city:			'北京',
  id:			'20002',
  mobile:		'13916382071',
  user_name:		'Duke',
  true_name:		'Guan',
  :avatar => File.open(File.join(Rails.root, 'app', 'assets','images','Duke.png')),
  email:		'13916382071@139.com',
  password:		'11111111',
  password_confirmation:'11111111',
  user_type:		'猎头',
  base_salary:		'10000',
  month_num:		'13',
  bonus:		'50000',
  housing:		'10200',
  transport:		'56000',
  birthday:		'1982-9-11',
  stock:		'',
  stock_num:	'',
  industry:		'管理岗位',
  focus_job1:		'CEO',
  focus_job2:		'Sales Director',
  focus_job3:		'HR Director',
  summaries_attributes:	{first:{content:'A results-driven professional, I am passionate about bringing a positive experience to my clients and value to my organization through: Accountable Execution and Passionate Delivery. With predominant experience in sales and business development in Asia, I have worked with clients ranging from MNCs to SMEs and government organizations throughout the region. I commit to providing a focussed, targeted and personal approach to my clients, operating with transparency, accountability and passion.'}},
  works_attributes:	
  			{first: {title:  'Executive Search Consultant',
	  			employer:'华德士',
				industry:'猎头',
				join_date:'2007-9-1',
				leave_date:'2014-12-1',
				job_scope:'Executive Search'
				}},
  educations_attributes:{first: {enter_school:'2001-9-1',
	  			leave_school:'2007-7-31',
				major:'history',
				degree:'master',
				school:'London University'}}
  			)
c=User.new(
  title:		'猎头顾问',
  city:			'广州',
  id:			'20003',
  mobile:		'13916320003',
  user_name:		'沈丽君',
  true_name:		'沈傲君',
  :avatar => File.open(File.join(Rails.root, 'app', 'assets','images','slj.png')),
  email:		'slj@test.com',
  password:		'11111111',
  password_confirmation:'11111111',
  user_type:		'猎头',
  base_salary:		'10000',
  month_num:		'13',
  bonus:		'50000',
  housing:		'10200',
  transport:		'56000',
  birthday:		'1982-9-11',
  stock:		'',
  stock_num:	'',
  industry:		'工业',
  focus_job1:		'销售经理',
  focus_job2:		'部门总监',
  focus_job3:		'财务总监',
  summaries_attributes:	{first:{content:'擅长工业销售，化工，医疗器械，包装电子，通讯等行业的人才推荐'}},
  works_attributes:	
  			{first: {title:  '猎头顾问',
	  			employer:'华德士',
				industry:'猎头',
				join_date:'2007-9-1',
				leave_date:'2014-12-1',
				job_scope:'Executive Search'
				}},
  educations_attributes:{first: {enter_school:'2001-9-1',
	  			leave_school:'2007-7-31',
				major:'chemistry',
				degree:'bachelor',
				school:'Nankai University'}}
  			)
d=User.new(
  title:		'猎头顾问',
  city:			'上海',
  id:			'20004',
  mobile:		'13916320004',
  user_name:		'天使之翼',
  true_name:		'天使之翼',
  :avatar => File.open(File.join(Rails.root, 'app', 'assets','images','天使之翼.png')),
  email:		'tszy@test.com',
  password:		'11111111',
  password_confirmation:'11111111',
  user_type:		'猎头',
  base_salary:		'10000',
  month_num:		'13',
  bonus:		'50000',
  housing:		'10200',
  transport:		'56000',
  birthday:		'1982-9-11',
  stock:		'',
  stock_num:	'',
  industry:		'快消',
  focus_job1:		'销售经理',
  focus_job2:		'部门总监',
  focus_job3:		'财务总监',
  summaries_attributes:	{first:{content:'擅长工业销售，化工，医疗器械，包装电子，通讯等行业的人才推荐'}},
  works_attributes:	
  			{first: {title:  '猎头顾问',
	  			employer:'Adecco',
				industry:'猎头',
				join_date:'2007-9-1',
				leave_date:'2014-12-1',
				job_scope:'Executive Search'
				}},
  educations_attributes:{first: {enter_school:'2001-9-1',
	  			leave_school:'2007-7-31',
				major:'chemistry',
				degree:'bachelor',
				school:'Nankai University'}}
  			)
e=User.new(
  title:		'猎头顾问',
  city:			'上海',
  id:			'20005',
  mobile:		'13916320005',
  user_name:		'陈大同',
  true_name:		'陈大同',
  :avatar => File.open(File.join(Rails.root, 'app', 'assets','images','陈大同.png')),
  email:		'cdt@test.com',
  password:		'11111111',
  password_confirmation:'11111111',
  user_type:		'猎头',
  base_salary:		'10000',
  month_num:		'13',
  bonus:		'50000',
  housing:		'10200',
  transport:		'56000',
  birthday:		'1982-9-11',
  stock:		'',
  stock_num:	'',
  industry:		'快消',
  focus_job1:		'销售经理',
  focus_job2:		'部门总监',
  focus_job3:		'财务总监',
  summaries_attributes:	{first:{content:'擅长工业销售，化工，医疗器械，包装电子，通讯等行业的人才推荐'}},
  works_attributes:	
  			{first: {title:  '猎头顾问',
	  			employer:'光辉国际',
				industry:'猎头',
				join_date:'2007-9-1',
				leave_date:'2014-12-1',
				job_scope:'Executive Search'
				}},
  educations_attributes:{first: {enter_school:'2001-9-1',
	  			leave_school:'2007-7-31',
				major:'chemistry',
				degree:'bachelor',
				school:'Nankai University'}}
  			)
f=User.new(
  title:		'猎头顾问',
  city:			'上海',
  id:			'20006',
  mobile:		'13916320006',
  user_name:		'Ramond',
  true_name:		'Ramond',
  :avatar => File.open(File.join(Rails.root, 'app', 'assets','images','Ramond.png')),
  email:		'r@test.com',
  password:		'11111111',
  password_confirmation:'11111111',
  user_type:		'猎头',
  base_salary:		'10000',
  month_num:		'13',
  bonus:		'50000',
  housing:		'10200',
  transport:		'56000',
  birthday:		'1982-9-11',
  stock:		'',
  stock_num:	'',
  industry:		'奢侈品',
  focus_job1:		'销售经理',
  focus_job2:		'部门总监',
  focus_job3:		'财务总监',
  summaries_attributes:	{first:{content:'擅长工业销售，化工，医疗器械，包装电子，通讯等行业的人才推荐'}},
  works_attributes:	
  			{first: {title:  '猎头顾问',
	  			employer:'海德思哲',
				industry:'猎头',
				join_date:'2007-9-1',
				leave_date:'2014-12-1',
				job_scope:'Executive Search'
				}},
  educations_attributes:{first: {enter_school:'2001-9-1',
	  			leave_school:'2007-7-31',
				major:'chemistry',
				degree:'bachelor',
				school:'Nankai University'}}
  			)
g=User.new(
  title:		'猎头顾问',
  city:			'上海',
  id:			'20007',
  mobile:		'13916320007',
  user_name:		'千寻',
  true_name:		'千寻',
  :avatar => File.open(File.join(Rails.root, 'app', 'assets','images','千寻.png')),
  email:		'qx@test.com',
  password:		'11111111',
  password_confirmation:'11111111',
  user_type:		'猎头',
  base_salary:		'10000',
  month_num:		'13',
  bonus:		'50000',
  housing:		'10200',
  transport:		'56000',
  birthday:		'1982-9-11',
  stock:		'',
  stock_num:	'',
  industry:		'复合肥料',
  focus_job1:		'销售经理',
  focus_job2:		'部门总监',
  focus_job3:		'财务总监',
  summaries_attributes:	{first:{content:'擅长工业销售，化工，医疗器械，包装电子，通讯等行业的人才推荐'}},
  works_attributes:	
  			{first: {title:  '猎头顾问',
	  			employer:'海德思哲',
				industry:'猎头',
				join_date:'2007-9-1',
				leave_date:'2014-12-1',
				job_scope:'Executive Search'
				}},
  educations_attributes:{first: {enter_school:'2001-9-1',
	  			leave_school:'2007-7-31',
				major:'chemistry',
				degree:'bachelor',
				school:'Nankai University'}}
  			)
a.skip_confirmation!
b.skip_confirmation!
c.skip_confirmation!
d.skip_confirmation!
e.skip_confirmation!
f.skip_confirmation!
g.skip_confirmation!
a.save!
b.save!
c.save!
d.save!
e.save!
f.save!
g.save!
